# Default values for kafka.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: kafka
  tag: v2.12.2.2.0-test
  pullPolicy: IfNotPresent
imagePullSecrets: my-secret

nameOverride: ""
fullnameOverride: ""
env:
  - name: KAFKA_HEAP_OPTS
    value : "-Xmx512M -Xms512M"
  - name: KAFKA_OPTS
    value: "-Dlogging.level=INFO"
zookeeper:
  connection: zookeeper-0.zookeeper-headless:2181,zookeeper-1.zookeeper-headless:2181,zookeeper-2.zookeeper-headless:2181
service:
  type: ClusterIP
  port: 9093

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  name: datadir
  size: "4Gi"
  storageClass: "managed-nfs-storage"

localVolume:
  enabled: false
  hostPath: /opt/data/kafkadata

podDisruptionBudget:
  maxUnavailable: 2  # Limits how many Zokeeper pods may be unavailable due to voluntary disruptions.

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
