apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    description: ""
  creationTimestamp: null
  labels:
    controller-uid: ac9388b9-1eed-11ea-885b-fa163e56c07c
    job-name: test-job
  name: test-job
  selfLink: /apis/batch/v1/namespaces/default/jobs/test-job
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: ac9388b9-1eed-11ea-885b-fa163e56c07c
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: ac9388b9-1eed-11ea-885b-fa163e56c07c
        job-name: test-job
      name: test-job
    spec:
      containers:
      - args:
        - '- l'
        command:
        - ls
        image: alpine:latest
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command:
              - ls
              - -l
          preStop:
            exec:
              command:
              - ls
              - -l
        name: container-0
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsConfig:
        options:
        - name: single-request-reopen
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: default-secret
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
